[package]
name = "jason"
version = "0.1.0"
edition = "2024"

[dependencies]

[dev-dependencies]
criterion = "0.8.2"

[[bench]]
name = "parse"
harness = false

[[bench]]
name = "serialize"
harness = false

[[bench]]
name = "pointer"
harness = false

[[bench]]
name = "diff"
harness = false

[[bench]]
name = "patch"
harness = false